### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by msaeltzer** [zweitstimme-org/candidate-timeseries#1]
Hey Marcel, Vielen Dank für die Daten, das ist schon mal sehr hilfreich. Habt ihr vor, das zugrunde liegende Modell auch zu veröffentlichen? Dann würde ich die Daten nochmal mit den Polling Results für das Jahr neu berechnen und man könnte es hier hochladen...

**Comment by mneunhoe** [comment]
Hey Marius,

die Modelle sind schon (seit vor der Wahl) im dataverse veröffentlicht: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/EDTKNW. Wenn du die Zeitreihen erweiterst, freuen wir uns natürlich über die Ergebnisse!

**Comment by msaeltzer** [comment]
Hey Marcel, vielen dank für den Code, das ist sehr hilfreich. Ich bin gerade mal durch euren Code durchgegangen. Ich glaube mit fehlt für die Wahlkreisprogrosen die file  `btw_candidates_1983-2017.csv' . Oder gibt es irgendwo einen startpunkt von dem man die Predictions für jeden Tag nur "updaten" muss?
LG Marius
